# Generated by Django 5.2.4 on 2025-07-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avator_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator',
            new_name='avatar',
        ),
    ]
